import chromadb

def load_data():
    # 500MB free tier
    railway_volume_path = "/usls_scholarships"
    chroma_client = chromadb.PersistentClient(path=railway_volume_path)
    collection = chroma_client.get_or_create_collection(name="USLS_SCHOLARSHIPS")

    if collection.count() == 0:
        collection.add(
            ids=[f"id{i}" for i in range(1, 15)],
            documents=[
                "Types of Scholarships in The University of St LaSalle: ACADEMIC SCHOLARSHIP AY 2025-2026 for Entering FRESHMEN link to scholarship: https://docs.google.com/forms/d/e/1FAIpQLSdxxASe1969YhM432JE8IpIflTRg8EgnkMEpINoGqXy4f891g/closedform, VARSITY ATHLETES GRANT link to scholarship: https://docs.google.com/forms/d/e/1FAIpQLScoNzUKe5PXKH5UCVInviifMdnwS7CaPRNogXFoMEnsErM7Cg/viewform, CULTURAL GRANT link to scholarship: https://docs.google.com/forms/d/e/1FAIpQLSezxMnFlvRpOJ61CzzArhg8-l2iUwUXQDmNIJYxHBOJZnB7NQ/closedform, STUDENT ASSISTANTSHIP PROGRAM (WORKING STUDENTS) link to scholarship: https://docs.google.com/forms/d/e/1FAIpQLSfRQ6inIEU-VayONQul0MJ6o3RYH8kLh_DEzSnCe9G0U-RxAQ/viewform",
                "FRESHMEN ACADEMIC SCHOLARSHIP: Valedictorian Scholarship, Grant An outright scholarship awarded to the Top/Rank 1 of the Grade 12 batch with a population of 150 or more graduates",
                "FRESHMEN ACADEMIC SCHOLARSHIP: Academic Scholarship, This scholarship is offered to students who belong to the Top 10% of their Grade 12 graduating batch (over-all ranking) or to the Rank 1 student in batches with less than 150 graduates. The top 100 qualifiers will undergo an interview with the Scholarship Committee. (Available academic slots: 80).",
                "FRESHMEN ACADEMIC SCHOLARSHIP: Valedictorian and Academic Scholarship Requirements: Online Scholarship Application with Scholarship Application Privacy Notice, Original Certificate of Ranking issued by their School Registrar or Principal, Photocopy of Entrance Exam Result (for ACADEMIC SCHOLARSHIP ONLY), Certified True Copy of Grade 12 Report Card, Good Moral Certificate, Proof of Parents Income: BIR 2316, if EMPLOYED; Employment Contract, if OFW; BIR, Certificate of Tax Exemption, if UNEMPLOYED; BIR Form 1701, if SELF-EMPLOYED; Senior Citizen Card, if RETIREES/ PENSIONER.",
                "FRESHMEN ACADEMIC SCHOLARSHIP: Top 3 Graduates from Liceo SHS, A full scholarship shall be given to the top 3 Liceo SHS graduates from each strand.",
                "FRESHMEN ACADEMIC SCHOLARSHIP: Top 3 Graduates from Liceo SHS Requirements, Requirement: Online Application Form for Top 3 with Scholarship Application Privacy Notice with this link: https://forms.gle/5BMFqH4PKZso9Lwd9, Endorsement from the Liceo Senior High School Registrar",
                "FRESHMEN ACADEMIC SCHOLARSHIP: Reminders is as follows please submit your application in a long white folder, labeled in pencil with your last name, first name, and middle initial. Example: De la Cruz, Juan T. Required Documents: Submit the hard copies of your scholarship application documents on or before May 16, 2025 to the Admissions and Scholarships Administration Office (ASAO). The required documents are as follows: Copy of your Report Card, Certificate of Ranking (Original), Proof of Income of your parents (Complete and clear copy).",
                "VARSITY ATHLETES GRANT: This grant is awarded to students with exceptional athletic abilities who successfully pass the tryouts conducted by the Institutional Varsity Sports Office. Grantees may receive a percentage discount on tuition and miscellaneous fees, covering up to 21 units, based on the evaluation and criteria set by the Institutional Varsity Sports Office and ASAO Varsity. The Events are as follows: Athletics - Men and Women, Badminton - Men and Women, Basketball - Men, Chess - Men and Women, Football - Men and Women, Lawn Tennis - Men and Women, Sepak Takraw - Men, Swimming - Men and Women, Table Tennis - Men and Women, Tae Kwon Do - Men and Women, Volleyball - Men and Women, PEP Squad, Dance Sport.",
                "CULTURAL GRANT: The University supports students with a passion for the arts through financial assistance in these groups, Chorale: For those with a passion for singing and creating harmony in various music styles. Musikat: For musicians with a passion for pop and modern music and performances. Ritmo Verde: For those with a passion for percussion and energetic drum beats. Vivace Strings: For those with a passion for playing classical and contemporary string music. Grupo Letras y Figuras: For artists with a passion for expressing culture through painting, sculpture, and other visual arts. Jean Baptiste Dance Company: For dancers with a passion for contemporary, hip-hop, and other dance forms. La Salle Film Society: For filmmakers and film lovers with a passion for creating and appreciating cinema. Maskara Theatre Ensemble: For actors and performers with a passion for drama, musicals, and experimental theatre. Production Support Group: For those with a passion for working behind the scenes, managing lighting, sound, and sets. Santermo Writers Guild: For writers with a passion for crafting poetry, stories, and essays. Iwag Photography: For photographers with a passion for capturing moments and telling stories through images. Members may enjoy up to a certain percentage discount on tuition and miscellaneous of up to 21 units depending on the evaluation and criteria set by Artists Hub (CAPC) and ASAO.",
                "CULTURAL GRANT: Requirements, Online Application Form with Scholarship Application Privacy Notice, Grades / Report Card, Performance Grades from the Moderators, Club Activities Joined/Participated for AY 2024-2025, Proof of Income of Parents: If employed - Please submit BIR Form 2316, If Self Employed, please submit complete BIR Form 1701, If Working Abroad, please submit employment contract, If no job - please submit BIR Cert of Tax Exemption. Barangay Certificate of Indigency or Low Income is not valid.",
                "STUDENT ASSISTANTSHIP PROGRAM (WORKING STUDENTS): This program provides opportunities to undergraduate students who may be considered as financially incapacitated but with the desire and dedication to finish their studies. This scholarship provides 100% discount on Tuition and Miscellaneous Fees, Capital Development, and Laboratory Fees, along with a monthly allowance. In return, each student must render 20 hours of service per week at their assigned office.",
                "STUDENT ASSISTANTSHIP PROGRAM (WORKING STUDENTS): Criteria for Eligibility: Open to continuing USLS students with at least 2 years remaining at the University or graduates of Liceo Senior High School, enrolled in any course EXCEPT BS Accountancy or BS Nursing. Liceo graduates who have transferred to other schools must enroll at USLS for at least one semester before applying to this program. Must have no failing grades in two consecutive semesters prior to application. Must be mentally and physically fit, with no medical health issues, and willing to be assigned to any office. Parent's annual income must not exceed 250,000 php. Must not be receiving any other scholarships from USLS or external donors. Willing to take 21 units ONLY per semester.",
                "STUDENT ASSISTANTSHIP PROGRAM (WORKING STUDENTS): Application Requirements: Online Application Form with Scholarship Application Privacy Notice, Application Letter addressed to Ms. Jennifer D. Pabalinas, MBA ASAO Director, Proof of Parents' Income: BIR 2316, if EMPLOYED;  Employment Contract, if OFW;  BIR Certificate of Tax Exemption, if UNEMPLOYED;  BIR Form 1701, if SELF-EMPLOYED; Senior Citizen Card, if RETIREE/ PENSIONER. Letter of Need from Parents, Photocopy of Grades (1st and 2nd semester for continuing College students, Grade 12 Report Card for Liceo Students), Latest Billing Statements for 3 consecutive months:  Water, Electric, Internet, Telephone, Recommendation from GEC.",
                "STUDENT ASSISTANTSHIP PROGRAM (WORKING STUDENTS): Reminders is as follows Please place your application in a legal-size brown envelope, labeled with your last name, first name, and middle initial using a marker. Example: de la Cruz, Juan T. Submit the hard copies of your scholarship application documents to the Admissions and Scholarships Administration Office (ASAO): Clear copies of Water, Electric, and Telephone Billing Statements, Complete and clear copy of your parents' Proof of Income, Copy of your Report Card or Certificate of Grades, Application letter"
            ]
        )

    print("Number of entries:", collection.count())

if __name__ == "__main__":
    load_data()
